version: "3.9"
services:
  backend:
    build: .
    container_name: dsa-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python app.py

  frontend:
    build: ./frontend
    container_name: dsa-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
